### ISSUE TITLE
Extension is not working on Edge

### ISSUE THREAD

**Issue by Gmanicus** [Gmanicus/Youtube-Tabs#3]
From @kanansnote
> Hi Grant! It's me again. The extension stopped working on Edge, and I'd like to know if you can investigate and fix this issue. Thanks.

I'll see if I can look into this today. Thanks for letting me know!

**Comment by Gmanicus** [comment]
Hi @kanansnote, I just installed the extension via edge, logged into Youtube, and the extension worked as expected.

Can you go into more detail as to what's broken, or does it look like the extension is completely disabled? (Can you make sure it's still enabled if it seems that way?)

If something is broken, can you also copy any errors you see related to Youtube Tabs via the Developer Console in the Edge browser?

**Comment by kanannuruyevs** [comment]
Ah, I actually wanted to open the new issue regarding this case, so it seems you did it for me :).

So here it is:

[2023-06-15_08-22-56.webm](https://github.com/Gmanicus/Youtube-Tabs/assets/99095303/d73d5754-f686-47e7-bf10-46f14ec80631)

I hope that I'm addressing the issue correctly.

**Comment by Gmanicus** [comment]
@kanansnote I was ultimately unable to reproduce the problem in Edge. However, thanks to your feedback, I have added a patch (960dad27fe0b099f6becf63c50fcf87fafbb9f2b) that should hopefully resolve the issue. That has been pushed to the Chrome Webstore and Firefox. You should see it on Firefox within 24hrs and Chrome within a few days. Please let me know if you still encounter the issue after you receive the patch.

**Comment by kanannuruyevs** [comment]
Hmm, there's some interesting stuff going on here. It seems that the extension doesn't work exactly when you add other channels beside the main one under YouTube Account Settings. I'm not sure why this happens because I didn't have any issues before with having two channels on YouTube, but now it appears to be a cause of the problem since I tried to create a new channel to test this issue by using Firefox and Edge.

I assumed that might be related to the conflict with the other extensions in Edge, which I did try to turn off/on some of them, but that wasn't the case. So, I didn't see a reason to go further to test with Firefox.

**Comment by kanannuruyevs** [comment]
@Gmanicus Hi Grant. Any updates regarding this case?

**Comment by Gmanicus** [comment]
Hi @kanansnote, sorry for the delay. You're saying that you encountered the same issue when you added a new channel through the "Switch Account" panel under your profile icon?
![Screenshot 2023-06-26 at 1 11 16 PM](https://github.com/Gmanicus/Youtube-Tabs/assets/11013079/d04e8f05-2e95-4d86-80cc-3eaf0f53aaec)

**Comment by kanannuruyevs** [comment]
Yes. That's correct.

**Comment by Gmanicus** [comment]
Hi Kanan. Unfortunately, I still can't reproduce the problem. I switched to a few alternative accounts, messed with the tabs, tried switching with the sidebar open/closed, etc. Didn't encounter any errors.

Are you seeing a new error message? If so, please share that here. That might help me try another solution.

**Comment by kanannuruyevs** [comment]
Alright. I'll just share the captured [video](https://drive.google.com/file/d/1BGDqh6lV9PndB7pToZ6kJ3zyJbuPUXKF/view?usp=sharing) here, so that may be helpful for you to understand the cause of the issue better.

**Comment by Gmanicus** [comment]
That is very odd behavior. Thank you for going through that, and yes, you are correct. We should see the 'Running version...' and 'We're in dark/light theme' messages if the extension loaded after switching accounts. The other errors were unrelated to the extension. For Youtube Tabs, the only errors would come from either `youtube-tabs.js` or `iro.min.js` (another package within the extension) I'll do some more digging.

**Comment by Gmanicus** [comment]
Was able to reproduce and got it fixed! Should hopefully see this patch pushed to the web stores within a few days.

**Comment by kanannuruyevs** [comment]
Well, that's great news! Happy to see that was effective to address the issue.

I've already received the update, and the extension seems to be working now. Just there is a minor issue that I've mentioned it in #4.
