### ISSUE TITLE
An idea to have a closing button to the right corner of the dialog box, and then moving the export button to next to import button.

### ISSUE THREAD

**Issue by kanannuruyevs** [Gmanicus/Youtube-Tabs#4]
I believe it would be adequate to have a specific button to exit the dialog box rather than just clicking anywhere. Please let me know if that would be a good idea to work with.

![Screenshot 2023-06-16 123444](https://github.com/Gmanicus/Youtube-Tabs/assets/99095303/c3a0533d-2a46-43af-988a-4f41b8bca8f5)

**Comment by Gmanicus** [comment]
Hi Kanan,

I can see that being intuitive for that modal since it takes up a large portion of the screen when it appears. That should be a simple addition. I'll try to remember to add that alongside the next patch.

P.S: I like your handwriting 👍

**Comment by Gmanicus** [comment]
Implemented in **2.0.8**

**Comment by kanannuruyevs** [comment]
Ok, Grant. I see the changes implemented successfully. Just, there is no description of what was done in the updated patch version in the dialog box, as you probably forgot to mention it.

There are a couple of other things I'd like to address, but I'm not sure if I'm ready to do that yet. I also consider not bothering you with my feature requests and issue reports while I think I need some time to finally convey them. 

So, thanks.
