### ISSUE TITLE
Conflicts with vidiq

### ISSUE THREAD

**Issue by Lucretia** [Gmanicus/Youtube-Tabs#8]
As the subject says.

With vidiq enabled in a normal window:

![image](https://github.com/Gmanicus/Youtube-Tabs/assets/570928/3f214f10-7e47-490c-ad51-7db5e1644251)

In a private window:

![image](https://github.com/Gmanicus/Youtube-Tabs/assets/570928/ce13c9fa-cc60-4710-bf8a-2b873009e46e)

I don't understand why it's different, vidiq doesn't show up properly in private windows either.

**Comment by Gmanicus** [comment]
How interesting. Thanks for the report, I'll look into fixing that 👍

**Comment by Gmanicus** [comment]
Fix is on the way! Looks like VidIQ was picking up on a generic class that Youtube Tabs was using and was placing buttons there.

Also, as for VidIQ not showing up in Private mode, that is default behavior for most browsers, but you can disable this in the options for each extension. For instance, if you're using Chrome, you would go to `chrome://extensions/`, then the extension details, and check `Allow in Incognito mode`.

**Comment by Gmanicus** [comment]
Resolved in v2.0.12. Should be released on Chrome in the next day or two. Might hit Firefox within the hour.

**Comment by Lucretia** [comment]
Thanks, that works now. As for vidiq, yeah I enable working in private windows anyway.
